### ISSUE TITLE
preserve state <> shareable link

### ISSUE THREAD

**Issue by jgcmarins** [sibelius/chart-playground#1]
## Description
It would be nice if the changes applied to the graph configuration reflected in the URL as query string params, allowing users to share a link that will determine the graph first render.

## Requirements
- [x] changing the graph configuration should change the url params
- [x] first render should check query string params to load a initial state, if valid

**Comment by sibelius** [comment]
check this https://github.com/pbeshai/use-query-params

**Comment by 0xthierry** [comment]
Hello everyone,

Is anyone working on this? or can I work on?

**Comment by 0xthierry** [comment]
This feature is already merged so I will close this PR
